### ISSUE TITLE
New Relic crash logs in Crashlytics/Sentry

### ISSUE THREAD

**Issue by Amit-Chakradhari** [newrelic/newrelic-ios-agent-spm#12]
## Description
We're seeing a lot of crashes due to Heap Corruption and all are pointing to New Relic. Please check and clarify if this is due to New Relic.

error for object 0x28378fe70: pointer being freed was not allocated
## Relevant Logs / Console output

0
libsystem_kernel.dylib
__pthread_kill + 8
1
libsystem_pthread.dylib
pthread_kill + 208
2
libsystem_c.dylib
abort + 124
3
libsystem_malloc.dylib
_malloc_put + 546
4
libsystem_malloc.dylib
malloc_report + 60
5
libsystem_malloc.dylib
free + 284
6
NewRelic
string - Line 1420
~Payload + 1420
7
NewRelic
std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const>>::~unique_ptr() + 16764
8
NewRelic
NewRelic::NetworkErrorEvent::NetworkErrorEvent(unsigned long long, double, char const*, char const*, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const>>, NewRelic::AttributeValidator&) + 16208
9
NewRelic
NewRelic::EventManager::newNetworkErrorEvent(unsigned long long, double, char const*, char const*, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const>>, NewRelic::AttributeValidator&) + 42636
10
NewRelic
NewRelic::AnalyticsController::createRequestErrorEvent(NewRelic::NetworkRequestData const&, NewRelic::NetworkResponseData const&, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const>>) + 58136
11
NewRelic
NewRelic::AnalyticsController::addNetworkErrorEvent(NewRelic::NetworkRequestData const&, NewRelic::NetworkResponseData const&, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const>>) + 59124
12
NewRelic
NRMAAnalytics.mm - Line 125
-[NRMAAnalytics addNetworkErrorEvent:withResponse:withPayload:] + 125
13
NewRelic
memory - Line 2620
__62+[NRMANetworkFacade noticeNetworkFailure:withTimer:withError:]_block_invoke + 2620
14
libdispatch.dylib
_dispatch_call_block_and_release + 24
15
libdispatch.dylib
_dispatch_client_callout + 16
16
libdispatch.dylib
_dispatch_root_queue_drain + 636
17
libdispatch.dylib
_dispatch_worker_thread2 + 172
18
libsystem_pthread.dylib
_pthread_wqthread + 224
19
libsystem_pthread.dylib
start_wqthread + 8

## Your Environment

Happening in all iOS versions, all devices
## Additional context

<img width="1138" alt="Screenshot 2022-10-01 at 3 19 19 PM" src="https://user-images.githubusercontent.com/85681566/193403599-40fbafe6-7891-4dff-87f2-429cd065038c.png">

**Comment by JustinRush-NR** [comment]
Hi @Amit-Chakradhari. This repo is used only for distribution of our iOS agent via Swift Package Manager. Please see the [New Relic support page](https://support.newrelic.com/s/) for help on implementation and issues. Thanks!
