### ISSUE TITLE
Bundle at 'X.app/Frameworks/Y.framework' contains disallowed nested bundles

### ISSUE THREAD

**Issue by twprzybysz** [newrelic/newrelic-ios-agent-spm#15]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Cannot send build to App Store Connect due to the following error:
`Invalid Bundle. The bundle at 'NewRelicTest.app/Frameworks/NewRelicModule.framework' contains disallowed nested bundles. With error code STATE_ERROR.VALIDATION_ERROR.90205 for id f2f30305-10b1-4890-a0b0-7b3677159bb2
`
## Steps to Reproduce

1. Create empty project with iOS target
2. Add module with one file
3. Add spm to this module
4. Write method in module which is responsible for NR token registration
5. Call that method from target
6. Set provisioning and archive
7. Upload project to App Store 

[NewRelicTest.zip](https://github.com/newrelic/newrelic-ios-agent-spm/files/9929385/NewRelicTest.zip)

## Expected Behavior
Build upload should be successful without any errors.

## Your Environment

Xcode 13.1, macOS Monterey, MBP M1 2020

**Comment by kgasienica** [comment]
Any prior on this?

**Comment by cdillard-NewRelic** [comment]
Hello @kgasienica, 
I just tried this with our latest agent version 7.4.0 and Xcode 14.2. I used your NewRelicTest.zip sample project and uploaded a test build to TestFlight including the NewRelic SPM dependency. It uploads to TestFlight and works without issue. Can you please try this project with latest Xcode and agent version and report back? Thanks!

**Comment by twprzybysz** [comment]
@cdillard-NewRelic  Conducted test on Xcode 14.2 - same problem.

**Comment by cdillard-NewRelic** [comment]
To make sure your NewRelicTest target can access NewRelic framework when building NewRelicModule you must add the NewRelic package to the NewRelicTest target.
See this screenshot. Your NewRelicTest target needs to have NewRelic package listed here.
<img width="890" alt="Screen Shot 2023-01-23 at 9 09 22 AM" src="https://user-images.githubusercontent.com/103527346/214089707-a2de80f0-0cea-4361-854f-f985fba0f50c.png">

Let us know if you still experience issues after changing which target lists NewRelic library.

**Comment by twprzybysz** [comment]
Ok so the update of iOS SDK to 14.x and embedding library solved the problem.
