### ISSUE TITLE
Crash Payload.hpp line 19 in NewRelic::Connectivity::Payload::~Payload()

### ISSUE THREAD

**Issue by AnshulMindbody** [newrelic/newrelic-ios-agent-spm#25]
[NOTE]: # 
^^ Payload.hpp line 19 in NewRelic::Connectivity::Payload::~Payload()^^ 

## Description
App is crashing. Please check attached file for the crashlog. 

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
[App-crashreport-03-28-2023_0317+0530.zip](https://github.com/newrelic/newrelic-ios-agent-spm/files/11085815/App-crashreport-03-28-2023_0317%2B0530.zip)

**Comment by AnshulMindbody** [comment]
@smalsam-newr  
 In the didFinishLaunchingWithOptions 
`  [NewRelic startWithApplicationToken:SecretHolder.newRelicToken];`
Other Analytics used - Pendo.

**Comment by gcazangi** [comment]
Also in didFinishLaunchingWithOptions, the other tool we use is Sentry.

**Comment by AnshulMindbody** [comment]
There two places where the crashes are identified 
Payload.hpp line 19 in NewRelic::Connectivity::Payload::~Payload()
string line 1459 in NewRelic::Connectivity::Payload::~Payload()

**Comment by AliaksandrRegino** [comment]
i also have a lot of crashes after updating to 7.4.3
string line 1459 in NewRelic::Connectivity::Payload::~Payload()
Payload.hpp line 19 in NewRelic::Connectivity::Payload::~Payload()

**Comment by dvshelley** [comment]
New Relic says that 7.4.4 will release next week with a patch for this crash.

**Comment by AnshulMindbody** [comment]
@dvshelley issue is still happening in the newer version 7.4.4.

**Comment by dvshelley** [comment]
@AnshulMindbody We are also still seeing the crates on 7.4.4. We have an open support ticket with New Relic about it. They are still working on it and do not have a specific timeline yet for when the problem will be solved. I think we are going to roll back to 7.4.2 while we wait for the fix. 

We didn't see these crashes when we were on 7.4.0, the last version we used prior to 7.4.3. Did anyone see these crashes on 7.4.2 or 7.4.1?

**Comment by AnshulMindbody** [comment]
@dvshelley yes you are correct issue is not happening on version 7.4.0.

**Comment by kirkbig** [comment]
we are also experiencing the crash in simulators using NewRelic v7.4.4 cc

```
#4	0x0000000103f6385c in NewRelic::Connectivity::Payload::~Payload() ()
#5	0x0000000103fc9348 in std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >::~unique_ptr() ()
#6	0x0000000103fc9200 in NewRelic::RequestEvent::RequestEvent(unsigned long long, double, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >, NewRelic::AttributeValidator&) ()
#7	0x0000000103ff9b6c in NewRelic::EventManager::newRequestEvent(unsigned long long, double, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >, NewRelic::AttributeValidator&) ()
#8	0x0000000103fbbe3c in NewRelic::AnalyticsController::addRequestEvent(NewRelic::NetworkRequestData const&, NewRelic::NetworkResponseData const&, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >) ()
#9	0x0000000103f9102c in -[NRMAAnalytics addNetworkRequestEvent:withResponse:withPayload:] ()
#10	0x0000000103fa2eb0 in __118+[NRMANetworkFacade noticeNetworkRequest:response:withTimer:bytesSent:bytesReceived:responseData:traceHeaders:params:]_block_invoke ()

```

**Comment by kirkbig** [comment]
> #4	0x0000000103f6385c in NewRelic::Connectivity::Payload::~Payload() ()
> #5	0x0000000103fc9348 in std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >::~unique_ptr() ()
> #6	0x0000000103fc9200 in NewRelic::RequestEvent::RequestEvent(unsigned long long, double, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >, NewRelic::AttributeValidator&) ()
> #7	0x0000000103ff9b6c in NewRelic::EventManager::newRequestEvent(unsigned long long, double, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >, NewRelic::AttributeValidator&) ()
> #8	0x0000000103fbbe3c in NewRelic::AnalyticsController::addRequestEvent(NewRelic::NetworkRequestData const&, NewRelic::NetworkResponseData const&, std::__1::unique_ptr<NewRelic::Connectivity::Payload const, std::__1::default_delete<NewRelic::Connectivity::Payload const> >) ()
> #9	0x0000000103f9102c in -[NRMAAnalytics addNetworkRequestEvent:withResponse:withPayload:] ()
> #10	0x0000000103fa2eb0 in __118+[NRMANetworkFacade noticeNetworkRequest:response:withTimer:bytesSent:bytesReceived:responseData:traceHeaders:params:]_block_invoke ()

and this is happening quite frequently for us.

**Comment by Ded77** [comment]
Same issue for us with version 7.4.3 and 7.4.4.

**Comment by ajith-heb** [comment]
Does any one know which version this issue has introduced? Is there any critical update that I may miss if I am downgrading SDK to 7.4.0 which was the last stable version integrated in our app?

**Comment by rbarbish** [comment]
Is this still happening for you all in 7.4.5? Currently using 7.4.3 and getting the crash at `NewRelic::Connectivity::Payload::~Payload() + 1459`. Thinking about downgrading to 7.4.0 is there is no support update on this.

**Comment by dvshelley** [comment]
Yes, the crashes still show in 7.4.5. We downgraded to 7.4.0 to work around the problem.
7.4.6 was just released today. The release notes do not mention this crash.

**Comment by smalsam-newr** [comment]
@dvshelley If you are still seeing this happen on 7.4.5, please contact support. We had not seen instances of this crash on 7.4.5.

**Comment by smalsam-newr** [comment]
Try release 7.4.8, or just released 7.4.9. A new feature flag, `NRFeatureFlag_NewEventSystem` was added, which contains a rewrite to the event system which should eliminate the ~Payload() crash.

**Comment by NicolasEymael** [comment]
@smalsam-newr ok, i will deploy a new version using 7.4.9 with this feature flag
if the crashes keep happening, i will reply here

**Comment by ihnatmoisieiev** [comment]
We're observing the same issue. Any working solution for now?

**Comment by NicolasEymael** [comment]
@smalsam-newr we found a new fatal error in our last version (using NewRelic 7.4.9 with NRFeatureFlag_NewEventSystem)
do you have any idea how to fix it?
```
Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x2c14 objc_retain + 16
1  libobjc.A.dylib                0x2c14 objc_retain_x0 + 16
2  NewRelic                       0x2c644 -[NRMAMobileEvent addAttribute:value:] + 50 (NRMAMobileEvent.m:50)
3  NewRelic                       0x410c8 -[NRMAAnalytics addRequestEvent:withResponse:withNRMAPayload:] + 323 (NRMAAnalytics.mm:323)
4  NewRelic                       0x550a4 __118+[NRMANetworkFacade noticeNetworkRequest:response:withTimer:bytesSent:bytesReceived:responseData:traceHeaders:params:]_block_invoke + 171 (NRMANetworkFacade.mm:171)
5  libdispatch.dylib              0x26a8 <redacted> + 32
6  libdispatch.dylib              0x4300 <redacted> + 20
7  libdispatch.dylib              0x744c <redacted> + 928
8  libdispatch.dylib              0x15be4 <redacted> + 392
9  libdispatch.dylib              0x163ec <redacted> + 156
10 libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
11 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

**Comment by cdillard-NewRelic** [comment]
Please use the latest New Relic iOS agent 7.4.11 which contains a new feature flag, NRFeatureFlag_NewEventSystem. Enable this feature flag which should remove the ~Payload() crash.
