### ISSUE TITLE
Build Phase Script for v7.4.0+

### ISSUE THREAD

**Issue by shahzadmajeed** [newrelic/newrelic-ios-agent-spm#26]
Which one is more accurate for 7.4.0+?

1. The [documentation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/installation/spm-installation/) says use following

```bash
ARTIFACT_DIR="${BUILD_DIR%Build/*}SourcePackages/artifacts"

SCRIPT=`/usr/bin/find "${SRCROOT}" "${ARTIFACT_DIR}" -type f -name run-symbol-tool | head -n 1`
/bin/sh "${SCRIPT}" "APP_TOKEN"
```

OR
2. [SPM README](https://github.com/newrelic/newrelic-ios-agent-spm) says use following
```bash
"${BUILD_DIR%/Build/*}/SourcePackages/artifacts/newrelic-ios-agent-spm/NewRelic.xcframework/Resources/run-symbol-tool" "APP_TOKEN"
```

Looks like both are trying to locate & execute `run-symbol-tool` but want to make sure document is consistent

**Comment by AnshulMindbody** [comment]
"${BUILD_DIR%/Build/*}/SourcePackages/artifacts/newrelic-ios-agent-spm/NewRelic.xcframework/Resources/run-symbol-tool" "APP_TOKEN"

this script is not working with Xcode 14.3, MAC OS 13.

**Comment by cdillard-NewRelic** [comment]
The following script will work now. Note the changed path where we added NewRelic folder.
```
"${BUILD_DIR%/Build/*}/SourcePackages/artifacts/newrelic-ios-agent-spm/NewRelic/NewRelic.xcframework/Resources/run-symbol-tool"
```

Thank you for reporting this. I can confirm there is an issue in the direct version of the script in Xcode 14.3. We'll update our documentation for this.  You can also use script 1.) which uses the find command and will work.

**Comment by AnshulMindbody** [comment]
Thank @cdillard-NewRelic  new script is working in Xcode 14.3.

**Comment by AnshulMindbody** [comment]
@cdillard-NewRelic I found one more issue after downgrading new relic version to 7.4.3 - 7.4.0 and uploading the dysm crash log is not symbolicated.
