### ISSUE TITLE
Source files for target NewRelicPackage should be located under 'Sources/NewRelicPackage'

### ISSUE THREAD

**Issue by nashfive** [newrelic/newrelic-ios-agent-spm#27]
## Description

Simply switching from package 7.4.3 to 7.4.4 yields the error: 

```
Source files for target NewRelicPackage should be located under 'Sources/NewRelicPackage', or a custom sources path can be set with the 'path' property in Package.swift
```

Your package structure is invalid/incomplete.
I had to create a local package with your `.binaryTarget` and use it instead of your package to fix this. 😮‍💨  

## Your Environment

Xcode 14.3

**Comment by alandeguz** [comment]
Happens for me, both Xcode 14.2 and 14.3

**Comment by mbruin-NR** [comment]
This was fixed in a previous update. Check the most recent release for the fix.
