### ISSUE TITLE
No such module 'NewRelic' and The signature of “NewRelic.xcframework” cannot be verified

### ISSUE THREAD

**Issue by ibrahimKoteish** [newrelic/newrelic-ios-agent-spm#32]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

1. Building NewRelic with Xcode 15.0 (beta) is failing due to 👇 (The signature of “NewRelic.xcframework” cannot be verified.)
2. After adding NewRelic using SPM Xcode still gives me `No such module 'NewRelic'` check attached

/Users/**/Library/Developer/Xcode/DerivedData/testNewRelic-bhufeyyoobszvucbmqyppsxpdwpi/SourcePackages/artifacts/newrelic-ios-agent-spm/NewRelic/NewRelic.xcframework:1:1 The signature of “NewRelic.xcframework” cannot be verified.

## Steps to Reproduce

Create a new SwiftUI Project on Xcode 15.0 and add NewRelic using SPM

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
New Relic Framework added successfully 

## Relevant Logs / Console output
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
Check Screenshots

## Your Environment
`Xcode 15 beta`
`swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)`
iOS 17

## Additional context
<img width="1139" alt="Screenshot 2023-06-06 at 11 32 42" src="https://github.com/newrelic/newrelic-ios-agent-spm/assets/112104422/ad8787de-12bc-475f-9eaf-d3a161470b6f">

[TIP]:  # ( Add any other context about the problem here. )
<img width="1139" alt="Screenshot 2023-06-06 at 11 29 24" src="https://github.com/newrelic/newrelic-ios-agent-spm/assets/112104422/a0d90054-1b17-43f0-be72-5847a7f53b90">

**Comment by madsolar8582** [comment]
This is related to a [change](https://developer.apple.com/documentation/Xcode/verifying-the-origin-of-your-xcframeworks) Apple made with no opt-out config (at least for SPM at the moment) to increase the "security of the supply chain". 

I've [posted](https://developer.apple.com/forums/thread/730955) on the forums for guidance.

In the meantime, if there is no workaround, could you please provide a timeline for compliance with the Xcode 15 changes? As of this moment, I have to remove New Relic to test on iOS/iPadOS 17 which means I do not have crash reporting, etc.

**Comment by timsearle** [comment]
Plus 1 to this. We'll need to disable New Relic on our beta iOS 17 branch until a new version of the SDK is shipped.

**Comment by madsolar8582** [comment]
Per [Apple Developer Relations](https://developer.apple.com/news/?id=av1nevon), privacy impacting SDKs will be required to be signed. Unfortunately, the [Verify app dependencies with digital signatures](https://developer.apple.com/videos/play/wwdc2023/10061/) did not cover SPM's options for overriding the current behavior like you can for manually attached XCFrameworks.

**Comment by theblixguy** [comment]
@madsolar8582 Is it possible to run the codesign command in the build phase? For example - https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/53

**Comment by rhys-rantmedia** [comment]
Yep, I can't test our app using NewRelic against the iOS 17 SDK until this is resolved.

**Comment by madsolar8582** [comment]
> @madsolar8582 Is it possible to run the codesign command as part of the build phase? For example - https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/53

Unfortunately I get the same error. I even tried forcing the script to run on all builds and place it before the Link Binary with Libraries build phase.

**Comment by zach-fuller** [comment]
Same here

**Comment by Senthil-Kaliathan** [comment]
I have tried in XCode Version 15.0 beta 2, still having the same issue.
Could we please share some timeline on when this issue will be addressed so that apps can be built with Xcode 15.0?
I really appreciate the help!

**Comment by cdillard-NewRelic** [comment]
Hello all, I'm Chris, an engineer with New Relic, sorry for the inconvenience caused by this issue with the framework. 
We plan to release an update containing Xcode 15 support by mid-July.

**Comment by laurentaylormarshall** [comment]
Hey @cdillard-NewRelic , just wanted to check in that this is still on track for mid-July, thanks!

**Comment by akshaaatt** [comment]
Any update on this?

**Comment by pedrofneves** [comment]
Same here. Any update?

**Comment by jeffhodsdon** [comment]
Same issue as well. Any update @cdillard-NewRelic ?

**Comment by cdillard-NewRelic** [comment]
Hello all, New Relic iOS agent 7.4.6 has been released.  [release link](https://github.com/newrelic/newrelic-ios-agent-spm/releases/tag/7.4.6)
Please update to this version as it includes a fix for framework signing to be compatible with Xcode 15
