### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by madsolar8582** [newrelic/newrelic-ios-agent-spm#33]
## Summary

Xcode 15 introduces [Privacy Manifests](https://developer.apple.com/documentation/bundleresources/describing_data_use_in_privacy_manifests) which will be required by Apple sometime in the future (presumably via App Store Connect). As a result, applications consuming New Relic will need to have an updated XCFramework with the privacy manifest implemented in order to continue using the agent.

## Desired Behavior

A new release of the New Relic agent is available with the privacy manifest included such that consuming applications can continue to distribute to the App Store without issue.

**Comment by shahzadmajeed** [comment]
+1 to this.. Currently, we cannot build app with Xcode 15 as it throws following error:

![Screenshot 2023-06-06 at 12 40 32 AM](https://github.com/newrelic/newrelic-ios-agent-spm/assets/1209459/c95cf001-c942-4eb6-8a78-a1327736fd25)

**Comment by timsearle** [comment]
+ 1 to this. We'll need to disable New Relic on our beta iOS 17 branch until a new version of the SDK is shipped.

**Comment by madsolar8582** [comment]
Based on my understanding, the current blocker is #32. This should be a future blocker once App Store Connect enables this feature.

**Comment by cdillard-NewRelic** [comment]
We are working to add this for a future release, thanks.

**Comment by isthisjoe** [comment]
+1

**Comment by bradwindy** [comment]
Also looking for an answer to when this might be released. I scanned the repo I work on that uses New Relic with the following tool:
https://github.com/bradwindy/iOS17-Required-Reason-API-Scanner

And you use `lstat`, `stat`, and `NSUserDefaults`, which requires you to include a privacy manifest explaining your use of this, as they fall under the `NSPrivacyAccessedAPICategoryFileTimestamp` and `NSPrivacyAccessedAPICategoryUserDefaults` API types respectively.

**Comment by chaithanyakumarks** [comment]
Hello @mbruin-NR ,

We were running the iOS 17 Required reason api scanner in our application with the help of 
[https://github.com/bradwindy/iOS17-Required-Reason-API-Scanner](https://github.com/bradwindy/iOS17-Required-Reason-API-Scanner)

We found that the NRTimer.h file is using the mach_absolute_time() API which is mentioned in the privacy required reason document. 

> Found potentially required reason API usage 'mach_absolute_time()' in '/Users/xxxxxxx/Library/Developer/Xcode/DerivedData/{App}-cowdtqoedigbogedjivwuwgobkiw/Build/Products/Debug-iphonesimulator/NewRelic.framework/Headers/NRTimer.h'
> Line numbers: 33 

Can you please add the [System boot time APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394)
in the Privacy manifest file of New relic SDK.

**Comment by mbruin-NR** [comment]
An entry for system boot time should already be present in our xcprivacy file.
You should be able to see the privacy manifest if you look in:
NewRelic.xcframework/ios-arm64/NewRelic.framework/PrivacyInfo.xcprivacy 
Do you see the file and is the key for system boot time present? If not you might be on an old version of the agent.
Our iOS repo is now open source so you can check out the xcprivacy file from source. https://github.com/newrelic/newrelic-ios-agent/blob/main/PrivacyInfo.xcprivacy

**Comment by lukasz-szyszkowski** [comment]
@cdillard-NewRelic when do you plan to release a version with Privacy Manifest support?
