### ISSUE TITLE
7.4.5 crashes when used with RxWebKit.

### ISSUE THREAD

**Issue by ji-no** [newrelic/newrelic-ios-agent-spm#34]
## Description
NewRelicAgent 7.4.5 and RxWebKit 2.0.1 are imported and crashes when executing webView.rx.decidePolicyNavigationAction.

## Steps to Reproduce
Reproduced in the following project.

https://github.com/ji-no/NewRelicCrash

## Expected Behavior
No crash

## Relevant Logs / Console output
![screenshot](https://github.com/newrelic/newrelic-ios-agent-spm/assets/19587945/f8fc98b8-b895-416d-a164-89f94b26621c)

## Your Environment
Xcode 14.2
iOS 16.2

## Additional context
No crash: NewRelic 7.4.3, RxWebKit 2.0.1
Crash: NewRelic 7.4.5, RxWebKit 2.0.1

**Comment by mbruin-NR** [comment]
Thank you for reporting this bug, we should have a fix available in the next release.

**Comment by cdillard-NewRelic** [comment]
A fix for this issue has been included in New Relic iOS agent 7.4.6
