### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by bamohammad** [newrelic/newrelic-ios-agent-spm#4]
I got repots that app crashing when starting 

## Description

App crashes on initializing and git this report from firbase craslaytics 
Thread
0  libsystem_kernel.dylib         0x290cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x5434 _pthread_cond_wait + 1248
2  libc++.1.dylib                 0x9efc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  NewRelic                       0x809a8 _hidden#7222_ + 100088
4  NewRelic                       0x80f7c _hidden#7244_ + 101580
5  NewRelic                       0x8111c _hidden#7247_ + 101996
6  libsystem_pthread.dylib        0x1bfc _pthread_start + 320
7  libsystem_pthread.dylib        0xa758 thread_start + 8

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

0  libsystem_kernel.dylib         0x290cc __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x5434 _pthread_cond_wait + 1248
2  libc++.1.dylib                 0x9efc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  NewRelic                       0x809a8 _hidden#7222_ + 100088
4  NewRelic                       0x80f7c _hidden#7244_ + 101580
5  NewRelic                       0x8111c _hidden#7247_ + 101996
6  libsystem_pthread.dylib        0x1bfc _pthread_start + 320
7  libsystem_pthread.dylib        0xa758 thread_start + 8

## Your Environment
IOS

**Comment by Sim-newrelic** [comment]
Couple suggestions here:

1. Could you look at how you are starting up firebase and the agent may need to swap the startup order for that?
2. Second couple you disable firebase completely if the first step does not work
3. If the issue still persists with firebase disabled could you send us sample code of your delegate files or where the activity is being started or initialized on startup

**Comment by Sim-newrelic** [comment]
If the issue continues to persist inside of new relic one there is a question mark on the top right corner of the home dashboard that will allow this issue to be seen by our entire support staff.

Thank you!

**Comment by cdillard-NewRelic** [comment]
Please use the latest New Relic iOS agent 7.4.11 which contains a new feature flag, NRFeatureFlag_NewEventSystem. Enable this feature flag which should remove the ~Payload() crash.
