### ISSUE TITLE
Post build dYSM script not working

### ISSUE THREAD

**Issue by calebwilson706** [newrelic/newrelic-ios-agent-spm#40]
## Description

Using the script 
```
ARTIFACT_DIR="${BUILD_DIR%Build/*}"
SCRIPT=`/usr/bin/find "${SRCROOT}" "${ARTIFACT_DIR}" -type f -name run-symbol-tool | head -n 1`
/bin/sh "${SCRIPT}" "APP_ID" --debug
```

## Steps to Reproduce
- Package version 7.4.6
- Xcode 14.3.1
- Script above
- Force crash

## Expected Behavior
Crash report should have symbols correctly

## Relevant Logs / Console output
logs from upload_dysm_results.log
```
New Relic: Starting dSYM upload script...
**** Using Region Aware URL: https://mobile-symbol-upload.eu01.nr-data.net
Successfully uploaded map: /Users/calebjw/Library/Caches/E575AFF7-37BC-4325-88E6-2ED3FB2A145C/mapArchive.zip
Successfully uploaded map: /Users/calebjw/Library/Caches/4349F237-6C75-40CD-BEAF-D2DD3EC59627/mapArchive.zip
```
## Additional context

New relic console shown here:
<img width="1039" alt="Screenshot 2023-08-08 at 17 42 27" src="https://github.com/newrelic/newrelic-ios-agent-spm/assets/71669491/1c32e79a-9049-488f-9ef1-586e7dc0eccf">

**Comment by smalsam-newr** [comment]
Hello. Can you please include what version of iOS you are experiencing this issue on?

**Comment by calebwilson706** [comment]
> Hello. Can you please include what version of iOS you are experiencing this issue on?

iOS 16.4 - more specifically iPad OS 16.4

**Comment by cdillard-NewRelic** [comment]
Please use our latest iOS agent version 7.4.11
