### ISSUE TITLE
New Relic headers are not added to the request while using urlSession.data(for: request)

### ISSUE THREAD

**Issue by subramka** [newrelic/newrelic-ios-agent-spm#43]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When utilising urlSession.data(for: request) in Swift for making network requests, we are encountering an unexpected behaviour where the New Relic headers are not being added to the request as intended. This issue is preventing the proper instrumentation of network requests by the New Relic SDK, impacting our ability to gather performance and monitoring data.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
## Steps to Reproduce
Use the urlSession.data(for: request) method to perform the network request.

```
do {
    let (data, response) = try await urlSession.data(for: request)
    // Process the response data
} catch let error {
    print("Error: \(error)")
}

```
Use proxy tools like proxyman to inspect the actual HTTP requests sent by your application.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

There is no new relic header added to the request by sdk
```
X-NewRelic-ID: XXXXX
newrelic: XXXXXX
```
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Apple M1 Max
Ventura 13.5.2 (22G91)
Xcode 15.2 (15C500b)
iOS - 16.7.2 
iOS Agent - 7.4.6

## Additional context
As a comparison, switching to using the traditional URLSession.dataTask method and observed New Relic headers are included.

```
let task = urlSession.dataTask(with: request) { data, response, error in
    // Process the response data
}
task.resume()
```

[TIP]:  # ( Add any other context about the problem here. )

**Comment by peter-major-apadmi** [comment]
This still isn't fixed as of 7.4.9, even though it was described as being fixed in the 7.4.8 release notes:

> Fixes async requests so they appear in distributed tracing.

We can see this because one of the SDK's is our app is making an API call (obviously via a non-async data task) and the `x-newrelic-id` header is present:
```
:method: GET
:scheme: https
:path: /content/key/redacted?depth=all&format=inlined
:authority: redacted.cdn.content.amplience.net
accept: application/json
content-type: application/json
x-newrelic-id: Vw4GWVRaABABVVNSBQEEXlQE
user-agent: redacted
accept-language: en-GB,en;q=0.9
accept-encoding: gzip, deflate, br
```

But our API call, which is using the async data task, does not have the `x-newrelic-id` header:
```
:method: GET
:scheme: https
:path: /uat/redacted/v1/api/subscriptions
:authority: redacted
content-type: application/json
accept: */*
authorization: Bearer redacted
x-correlation-id: 0593512A-F4C7-425C-8131-385BD5527AE4
x-firebase-appcheck: Bearer redacted
accept-encoding: gzip, deflate, br
cache-control: no-cache
x-component: ios
accept-language: en-GB,en;q=0.9
user-agent: redacted

**Comment by sky-tiagoornelas** [comment]
@peter-major-apadmi just out of curiosity, did you try enabling the `NRFeatureFlag_SwiftAsyncURLSessionSupport` FF that comes with the SDK? I was doing some tests with version 7.4.8 this week and we got the `x-newrelic-id` present in all requests. The strange thing was, the header was being sent with that Feature Flag both activated and deactivated.

**Comment by peter-major-apadmi** [comment]
Hi @sky-tiagoornelas. Thanks for your response.
Yes I've got the feature flag enabled.
Here's how I start the agent:
```
            NewRelic.enableFeatures([
                NRMAFeatureFlags.NRFeatureFlag_SwiftAsyncURLSessionSupport,
                NRMAFeatureFlags.NRFeatureFlag_NewEventSystem])
            NewRelic.disableFeatures(NRMAFeatureFlags.NRFeatureFlag_AppStartMetrics)
            NewRelic.start(withApplicationToken: environmentConfiguration.newRelicToken)
            NewRelic.addHTTPHeaderTracking(for: [HttpHeaderKey.correlationId.rawValue])
```

**Comment by sky-tiagoornelas** [comment]
Strange then how I'm getting that header to go out 🤔

**Comment by smalsam-newr** [comment]
Hello. We have a fix for this issue that we are working on. We anticipate releasing it early next week.

**Comment by peter-major-apadmi** [comment]
Thank you for looking into this. I'll keep an eye out for the new release.

**Comment by peter-major-apadmi** [comment]
Hi there. Any news on the progress of the next release to fix this issue?

**Comment by smalsam-newr** [comment]
@peter-major-apadmi  We have merged the fix in, which you can see in the PR linked in our new open-source repository. We are targeting a release sometime this week.

**Comment by smalsam-newr** [comment]
@peter-major-apadmi @subramka Version 7.4.10, which should have a fix for this issue, has been deployed.
