### ISSUE TITLE
Is 7.4.10 suppose to be released soon?

### ISSUE THREAD

**Issue by shahzadmajeed** [newrelic/newrelic-ios-agent-spm#45]
Hi,

When are we releasing 7.4.10 and do we have details on what's included in that version? I'm looking to upgrade our current version and want to see if we want to want for 7.4.10

-Shahzad

**Comment by mbruin-NR** [comment]
Sorry for the confusion but 7.4.10 was released 2 weeks ago with out the release notes for this repo being updated. I'll get those notes added but you should be able to use 7.4.10. Let me know if that is not the case.
