### ISSUE TITLE
NRFeatureFlag_BackgroundReporting Not Working

### ISSUE THREAD

**Issue by amkomatz** [newrelic/newrelic-ios-agent-spm#52]
I'm trying to use the new background reporting flag, but it doesn't appear to be working. 

## Description

I have set up the background modes, and have added my background task identifier. My background task is running as expected, I have verified this through remote logging. Still, no NewRelic data is coming through while the background task is running.

The following is at the top of my app delegate. 

```
NewRelic.enableFeatures(NRMAFeatureFlags.NRFeatureFlag_BackgroundReporting)
NewRelic.setApplicationVersion(UIApplication.appVersion)
NewRelic.setApplicationBuild(UIApplication.buildNumber)
NewRelic.start(...)
```

## Expected Behavior

NewRelic data should be flowing every time my background task runs. No events, networking data, etc., are making it through.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

iOS 17.5.1
NewRelic SDK version 7.4.12

**Comment by amkomatz** [comment]
I'm even getting a success result from `NewRelic.recordCustomEvent(...)`, but the events are not making it through

**Comment by mbruin-NR** [comment]
There was a bug in the iOS agent where if you foregrounded your app before the background harvest executed those events wouldn't get sent. That bug was fixed in a previous version of the agent. Please update to the newest iOS agent version
