### ISSUE TITLE
When we updated to NR v7.5, the number of reported "hangs" jumped significantly

### ISSUE THREAD

**Issue by dvshelley** [newrelic/newrelic-ios-agent-spm#55]
## Description

We see *a lot* of hangs since we updated to NR v7.5. 
- Go to Xcode
- open Organizer
- select Reports -> Hangs
- lots of hangs related to NRMAHarvester

![Screenshot 2024-08-20 at 3 03 11 PM](https://github.com/user-attachments/assets/5cd32fb7-607e-4c37-aac4-c27147c96ca9)

Is this an issue that others are seeing a lot of?

Is there a fix to 7.5 coming? Is NR aware of this issue?

## Relevant Logs / Console output

See above screenshot

## Your Environment

We are building with Xcode 15.3, through SPM. We target iOS 16, 17.

**Comment by cdillard-NewRelic** [comment]
Hello @dvshelley , Thank you for reporting this. We have not seen other reports of this.  We changed some handling in setUserId in 7.5.0. If possible can you remove usage of setUserId? We have created a ticket to investigate this issue on our side for a future release.

**Comment by dvshelley** [comment]
Thanks for getting back with me. I will watch for a new release that addresses the issue.

**Comment by Jojr** [comment]
@dvshelley I noticed the same here after updating to NR v7.5. 
Did you manage to resolve this hang?

![nr-hang](https://github.com/user-attachments/assets/a0f8d216-883d-444f-9511-14b196d2e02a)

**Comment by dvshelley** [comment]
> @dvshelley I noticed the same here after updating to NR v7.5. Did you manage to resolve this hang?
> 

We initially worked around the problem by going back to NR v7.4. We have since tried v7.5.2. It does not have the same hang problem.
