### ISSUE TITLE
iOS Agent crash

### ISSUE THREAD

**Issue by ghost** [newrelic/newrelic-ios-agent-spm#6]
## Description

New relic agent crash. Agent version 7.3.4

## Steps to Reproduce

Random crash

## Relevant Logs / Console output

Thread
0  libsystem_kernel.dylib         0x281ac __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x5458 _pthread_cond_wait + 1192
2  libc++.1.dylib                 0xd328 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  NewRelic                       0x80958 NewRelic::WorkQueue::task_thread() + 100088
4  NewRelic                       0x80f2c std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::__execute() + 101580
5  NewRelic                       0x810cc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<void (NewRelic::WorkQueue::*)(), NewRelic::WorkQueue*> >*> >(void*) + 101996
6  libsystem_pthread.dylib        0x1b40 _pthread_start + 320
7  libsystem_pthread.dylib        0xa768 thread_start + 8

## Your Environment

iOS 14 and iOS 15. All kind of iPhones.

**Comment by cdillard-NewRelic** [comment]
@jesus-verse Can you please retry your app with the latest New Relic iOS Agent 7.4.0? Crash fixes were included in this area and could resolve your issue. Thanks!

**Comment by cdillard-NewRelic** [comment]
Please use the latest New Relic iOS agent 7.4.11 which contains a new feature flag, NRFeatureFlag_NewEventSystem. Enable this feature flag which should remove the ~Payload() crash.
