### ISSUE TITLE
add release notes t https://github.com/newrelic/newrelic-ios-agent-spm

### ISSUE THREAD

**Issue by kirkbig** [newrelic/newrelic-ios-agent-spm#9]
## Summary

in order to be able to know whether i need to spend the time to update my Swift Package, i would like some easily digestible release notes.

**Comment by smalsam-newr** [comment]
Hello. We'll add the link to the release notes to the README in a second, but until then, here they are! https://docs.newrelic.com/docs/release-notes/mobile-release-notes/xcframework-release-notes/

**Comment by cdillard-NewRelic** [comment]
The release notes are now contained in this repos README. https://github.com/newrelic/newrelic-ios-agent-spm#release-notes
